<a href="https://colab.research.google.com/github/jtracos/intro_python_for_data/blob/main/3.Intro_pandas_n_graphics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## Pandas essentials 

### Hoja de datos en pandas

In [ ]:
data = np.random.randint(0,40, size=(100,3)) #datos
df = pd.DataFrame(data=data, columns=["VAR 1","VAR 2","VAR 3"]) #data frame
from IPython.display import display # ignorar(es estetica)
display(df.head(10))

### estadisticas generales

In [ ]:
#estadisticas básicas
df.describe()

In [ ]:
#informacion del contenido del data frame
df.info()

In [ ]:
#tipos de datos de los atributos almacenados
df.dtypes

### seleccion de los datos(broadcasting)

Los datos se seleccionan mediante los indices y nombre de atributos

In [ ]:
#seleccion de datos
print(df.loc[1:4])

In [ ]:
#cambiar valores de entrada
df.loc[3]=[np.nan,1.,1.]
df.loc[4,"VAR 2"] = np.nan
df.loc[5,"VAR 3"] = np.nan
display(df.head(10))


### manipulacion de los datos

*.drop* para eliminar renglones o columnas por *indice* o *atributo*

In [ ]:
#elimina elementos por columna o renglos elegidos
df = df.drop("VAR 3", axis=1)
display(df.head(10))

In [ ]:
#eliminar la entrada 0
df = df.drop(0)
display(df.head(10))

In [ ]:
#eliminar los entradas con indice > 9
df = df.drop(df.index[df.index<9])
display(df.head(10))


`*.map*` permite aplicar reglas medianta funciones *lambda*

In [ ]:
#funcion para clasificar los datos
def select_classes(val):
  if val < 10.:
    clas = 0
  elif val < 20.:
    clas = 1
  elif val < 30.:
    clas = 2
  else:
    clas = 3
  return clas

In [ ]:
#categorizacion de los datos
df["CLASE VAR 2"] = df["VAR 2"].map(lambda x: select_classes(x))
df

### graficos

In [ ]:
def set_layout(figsize = (8,8)):
  fig = plt.figure(figsize=figsize)
def end_set():
  plt.grid()
  plt.legend()
  _ = plt.show()

In [ ]:
set_layout()
for name in df.columns:
  plt.scatter(df.index,df[name], label=name)
plt.xlabel("INDICE")
plt.ylabel("UNIDADES")
end_set()

In [ ]:
fig, ax = plt.subplots(1,2)
fig.set_figheight(6)
fig.set_figwidth(12)
_ = ax[0].hist(df["VAR 1"].values)
_ = ax[1].hist(df["VAR 2"].values)
_ = plt.show()

## arreglos de n dimensiones

In [26]:
a = np.random.randint(-100,100,(4,3,2))
a

array([[[ 54,  -4],
        [ 11,  25],
        [ 34,  -3]],

       [[ 97,  92],
        [-16,  97],
        [ 74, -48]],

       [[ 20, -40],
        [ 70,  18],
        [-48, -19]],

       [[ 69, -71],
        [-91, -72],
        [-60, -67]]])

In [27]:
a.sum(axis=0)

array([[ 240,  -23],
       [ -26,   68],
       [   0, -137]])

In [28]:
a.sum(axis=1)

array([[  99,   18],
       [ 155,  141],
       [  42,  -41],
       [ -82, -210]])

In [29]:
a.sum(axis=2)

array([[  50,   36,   31],
       [ 189,   81,   26],
       [ -20,   88,  -67],
       [  -2, -163, -127]])

#Anexos:

## funciones lambda

sirve para la declaracion implicita de variables. Sintaxis simple

In [ ]:
 aceptar = lambda x, umbral: True if x <= umbral else False

In [ ]:
aceptar(40,20)

## declaracion de funciones

La estructura basica de una función es muy sencilla

`def nombre_funcion(entrada_1, entrada_2):`

`. . instrucciones`

`. . return output`

La identación es vital en python.

 Ejemplo de funciones son `select_classes` o `set_layout`